# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rolling Annualized Realized Volatility (C++)
#'
#' Computes rolling standard deviation of log returns, annualized by sqrt(252).
#' Much faster than pure R for large vectors (e.g., 5000+ daily observations).
#'
#' @param x     Numeric vector of log returns (pre-computed)
#' @param window Integer rolling window length in trading days
#' @return Numeric vector of same length as x; first (window-1) values are NA
#' @export
rolling_vol_cpp <- function(x, window) {
    .Call('_fin451app_rolling_vol_cpp', PACKAGE = 'fin451app', x, window)
}

#' Rolling Pairwise Beta (OLS hedge ratio) in C++
#'
#' For each window, computes beta = cov(x, y) / var(y).
#' Used for hedge ratio estimation across the term structure.
#'
#' @param x      Numeric vector (instrument to hedge)
#' @param y      Numeric vector (hedging instrument)
#' @param window Integer rolling window
#' @return Numeric vector of rolling betas
#' @export
rolling_beta_cpp <- function(x, y, window) {
    .Call('_fin451app_rolling_beta_cpp', PACKAGE = 'fin451app', x, y, window)
}

